"""
LangChain chains for MediGuide AI.

This module contains:
1. ChatOpenAI model configuration
2. Reusable LLMChain for medical assessment
3. Helper function for running the assessment
4. System/Human/AI message demonstration
"""

from langchain_openai import ChatOpenAI
from langchain_classic.chains import LLMChain
from langchain_core.messages import (
    SystemMessage,
    HumanMessage,
    AIMessage,
)

from src.config import OPENAI_API_KEY, DEFAULT_MODEL
from src.prompts import (
    MEDICAL_CHAT_PROMPT,
    SYSTEM_PROMPT,
    JSON_SCHEMA_INSTRUCTION,
)


# ============================================================
# 1. BUILD THE OPENAI CHAT MODEL
# ============================================================

def create_llm(api_key=None):
    """
    Create and return the OpenAI Chat model.

    The API key can be provided by the current user. The .env value is
    retained as a fallback for non-UI callers.
    """

    api_key = api_key or OPENAI_API_KEY

    if not api_key:
        raise ValueError(
            "OpenAI API key is missing. "
            "Please enter it in the app or add it to your .env file."
        )

    llm = ChatOpenAI(
        model=DEFAULT_MODEL,
        temperature=0,
        api_key=api_key,
    )

    return llm


# ============================================================
# 2. CREATE THE REUSABLE LLMCHAIN
# ============================================================

def get_medical_chain(api_key=None):
    """Create the model and chain only when an assessment is requested."""

    return LLMChain(
        llm=create_llm(api_key),
        prompt=MEDICAL_CHAT_PROMPT,
        verbose=False,
    )


# ============================================================
# 3. FUNCTION TO RUN THE MEDICAL ASSESSMENT
# ============================================================

def run_medical_assessment(
    age,
    gender,
    symptoms,
    duration,
    severity,
    existing_conditions,
    medications,
    notes,
    language,
    api_key=None,
):
    """
    Run the reusable medical assessment chain.

    Returns the raw text generated by the LLM.
    """

    result = get_medical_chain(api_key).invoke(
        {
            "age": age,
            "gender": gender,
            "symptoms": symptoms,
            "duration": duration,
            "severity": severity,
            "existing_conditions": existing_conditions,
            "medications": medications,
            "notes": notes,
            "language": language,
            "system_prompt": SYSTEM_PROMPT,
            "json_schema_instruction": JSON_SCHEMA_INSTRUCTION,
        }
    )

    return result


# ============================================================
# 4. SYSTEM / HUMAN / AI MESSAGE DEMO
# ============================================================

# ============================================================
# 4. RAW SYSTEM / HUMAN / AI MESSAGE DEMO
# ============================================================

def create_message_demo(patient_information):
    """
    Demonstrate the three basic LangChain message types:

    SystemMessage
    HumanMessage
    AIMessage

    This function does NOT call the OpenAI API.
    It simply demonstrates how a conversation can be represented
    using LangChain message objects.
    """

    system_message = SystemMessage(
        content=SYSTEM_PROMPT
    )

    human_message = HumanMessage(
        content=patient_information
    )

    ai_message = AIMessage(
        content=(
            "This is an example AIMessage. "
            "In the real application, this message will be generated "
            "by ChatOpenAI."
        )
    )

    messages = [
        system_message,
        human_message,
        ai_message,
    ]

    return messages

# ============================================================
# 5. TEST THE CHAIN DIRECTLY
# ============================================================

if __name__ == "__main__":

    result = run_medical_assessment(
        age=25,
        gender="Female",
        symptoms="Runny nose and sore throat",
        duration="1-3 days",
        severity=2,
        existing_conditions="None",
        medications="None",
        notes="No other relevant information.",
        language="English",
    )

    print("\n--- LLM RESPONSE ---\n")

    # Depending on the installed LangChain version,
    # LLMChain.invoke() may return a dictionary.
    print(result)

# ============================================================
# 5. STREAMING GENERATOR
# ============================================================

def stream_narrative(
    age,
    gender,
    symptoms,
    duration,
    severity,
    existing_conditions,
    medications,
    notes,
    language,
    api_key=None,
):
    """
    Stream a human-readable medical guidance response.

    Uses ChatOpenAI's .stream() method and yields each
    non-empty content chunk.
    """

    messages = MEDICAL_CHAT_PROMPT.format_messages(
        age=age,
        gender=gender,
        symptoms=symptoms,
        duration=duration,
        severity=severity,
        existing_conditions=existing_conditions,
        medications=medications,
        notes=notes,
        language=language,
        json_schema_instruction=JSON_SCHEMA_INSTRUCTION,
    )

    for chunk in create_llm(api_key).stream(messages):

        if chunk.content:
            yield chunk.content